// 三郷市例規集 - 全条例データ
// 内容現在 令和7年10月3日
// https://www1.g-reiki.net/misato/

const allOrdinanceData = [
    // ===== 第1編 総規 =====
    { id: 1, title: '三郷市役所の位置を定める条例', category: '総規・基本', keywords: ['市役所', '位置', '庁舎'], summary: '三郷市役所の位置を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000001.html' },
    { id: 2, title: '町を市とする処分', category: '総規・基本', keywords: ['市制施行', '三郷市'], summary: '三郷町を三郷市とする処分。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000002.html' },
    { id: 3, title: '三郷市の休日を定める条例', category: '総規・基本', keywords: ['休日', '祝日', '閉庁'], summary: '市の休日を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000005.html' },
    { id: 4, title: '三郷市民憲章', category: '総規・基本', keywords: ['市民憲章', '理念', '宣言'], summary: '三郷市民の行動規範となる憲章。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000006.html' },
    { id: 5, title: '三郷市章', category: '総規・基本', keywords: ['市章', 'シンボル', 'マーク'], summary: '三郷市の市章を定める。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000007.html' },
    { id: 6, title: '三郷市旗', category: '総規・基本', keywords: ['市旗', 'シンボル', '旗'], summary: '三郷市の市旗を定める。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000008.html' },
    { id: 7, title: '三郷市民の歌', category: '総規・基本', keywords: ['市歌', '歌', '音楽'], summary: '三郷市民の歌を定める。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000009.html' },
    { id: 8, title: '市の木、市の花', category: '総規・基本', keywords: ['市の木', '市の花', 'シンボル'], summary: '市の木と市の花を定める。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000626.html' },
    { id: 9, title: '市の鳥', category: '総規・基本', keywords: ['市の鳥', 'シンボル', '鳥'], summary: '市の鳥を定める。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000757.html' },
    { id: 10, title: '三郷市交通安全都市宣言', category: '総規・基本', keywords: ['交通安全', '宣言', '都市'], summary: '交通安全都市宣言。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000010.html' },
    { id: 11, title: '三郷市非核平和都市宣言', category: '総規・基本', keywords: ['非核', '平和', '宣言'], summary: '非核平和都市宣言。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000011.html' },
    { id: 12, title: '三郷市スポーツ健康都市宣言', category: '総規・基本', keywords: ['スポーツ', '健康', '宣言'], summary: 'スポーツ健康都市宣言。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000012.html' },
    { id: 13, title: '日本一の読書のまち宣言', category: '総規・基本', keywords: ['読書', '日本一', '宣言', '図書館'], summary: '日本一の読書のまち宣言。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00001008.html' },
    { id: 14, title: '三郷市自治基本条例', category: '総規・基本', keywords: ['自治', '基本条例', '市民参加', '協働'], summary: '自治の基本理念、市民参加、協働のまちづくりの基本を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000897.html' },
    { id: 15, title: '三郷市公告式条例', category: '総規・基本', keywords: ['公告', '告示', '公布'], summary: '条例等の公布方法を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000013.html' },
    { id: 16, title: '三郷市表彰条例', category: '総規・基本', keywords: ['表彰', '功績', '栄誉'], summary: '市の表彰に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000014.html' },

    // ===== 第2編 議会 =====
    { id: 17, title: '三郷市議会基本条例', category: '議会', keywords: ['議会', '基本条例', '議員', '民主主義'], summary: '議会運営の基本理念と議員の責務を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000965.html' },
    { id: 18, title: '三郷市議会の議員の定数を定める条例', category: '議会', keywords: ['議員定数', '定数', '議会'], summary: '議会議員の定数を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000017.html' },
    { id: 19, title: '三郷市議会定例会条例', category: '議会', keywords: ['定例会', '議会', '会議'], summary: '議会定例会の回数等を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000018.html' },
    { id: 20, title: '三郷市議会委員会条例', category: '議会', keywords: ['委員会', '常任委員会', '議会'], summary: '議会の委員会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000020.html' },
    { id: 21, title: '三郷市議会会議規則', category: '議会', keywords: ['会議規則', '議事', '議会運営'], summary: '議会の会議運営に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000021.html' },
    { id: 22, title: '三郷市議会傍聴規則', category: '議会', keywords: ['傍聴', '公開', '市民参加'], summary: '議会傍聴に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000022.html' },
    { id: 23, title: '三郷市議会議員政治倫理条例', category: '議会', keywords: ['政治倫理', '議員', '倫理'], summary: '議員の政治倫理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00001214.html' },
    { id: 24, title: '三郷市議会政務活動費の交付に関する条例', category: '議会', keywords: ['政務活動費', '議員', '交付'], summary: '政務活動費の交付に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000639.html' },
    { id: 25, title: '三郷市議会議員の請負の状況の公表に関する条例', category: '議会', keywords: ['請負', '公表', '透明性'], summary: '議員の請負状況の公表に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00001227.html' },
    { id: 26, title: '三郷市議会事務局設置条例', category: '議会', keywords: ['事務局', '議会', '組織'], summary: '議会事務局の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000024.html' },
    { id: 27, title: '三郷市議会の個人情報の保護に関する条例', category: '議会', keywords: ['個人情報', '保護', 'プライバシー'], summary: '議会における個人情報保護に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00001184.html' },

    // ===== 第3編 執行機関 =====
    { id: 28, title: '三郷市行政組織条例', category: '執行機関', keywords: ['行政組織', '部', '課', '組織'], summary: '市の行政組織を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000027.html' },
    { id: 29, title: '三郷市役所出張所設置条例', category: '執行機関', keywords: ['出張所', '窓口', 'サービス'], summary: '市役所出張所の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000031.html' },
    { id: 30, title: '三郷市行政改革推進委員会条例', category: '執行機関', keywords: ['行政改革', '推進', '効率化'], summary: '行政改革推進委員会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000035.html' },
    { id: 31, title: '三郷市まちづくり委員会条例', category: '執行機関', keywords: ['まちづくり', '委員会', '市民参加'], summary: 'まちづくり委員会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000041.html' },
    { id: 32, title: '三郷市情報公開条例', category: '執行機関', keywords: ['情報公開', '公文書', '透明性', '市民の知る権利'], summary: '市の情報公開に関する条例。市民の知る権利を保障。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000050.html' },
    { id: 33, title: '三郷市個人情報の保護に関する法律施行条例', category: '執行機関', keywords: ['個人情報', '保護', 'プライバシー'], summary: '個人情報保護法の施行に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000053.html' },
    { id: 34, title: '三郷市情報公開・個人情報保護審査会条例', category: '執行機関', keywords: ['審査会', '情報公開', '個人情報'], summary: '情報公開・個人情報保護に関する審査会の設置条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000055.html' },
    { id: 35, title: '三郷市行政手続条例', category: '執行機関', keywords: ['行政手続', '処分', '申請', '不利益処分'], summary: '行政手続の透明性・公正性を確保する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000059.html' },
    { id: 36, title: '三郷市行政手続等における情報通信の技術の利用に関する条例', category: '執行機関', keywords: ['電子申請', 'オンライン', 'デジタル化'], summary: '行政手続のオンライン化に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000062.html' },
    { id: 37, title: '三郷市行政不服審査法関係手数料徴収条例', category: '執行機関', keywords: ['行政不服審査', '手数料', '不服申立て'], summary: '行政不服審査に関する手数料の条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000064.html' },
    { id: 38, title: '三郷市行政不服審査会条例', category: '執行機関', keywords: ['行政不服審査', '審査会', '救済'], summary: '行政不服審査会の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000065.html' },
    { id: 39, title: '三郷市個人番号の利用及び特定個人情報の提供に関する条例', category: '執行機関', keywords: ['マイナンバー', '個人番号', '番号制度'], summary: 'マイナンバーの利用に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000067.html' },
    { id: 40, title: '三郷市選挙管理委員会規程', category: '執行機関', keywords: ['選挙', '選挙管理', '投票'], summary: '選挙管理委員会に関する規程。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000071.html' },
    { id: 41, title: '三郷市議会議員又は三郷市長の選挙における選挙運動用自動車の使用等の公営に関する条例', category: '執行機関', keywords: ['選挙', '公営', '選挙運動'], summary: '選挙運動の公費負担に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000077.html' },
    { id: 42, title: '三郷市選挙公報発行条例', category: '執行機関', keywords: ['選挙公報', '選挙', '情報提供'], summary: '選挙公報の発行に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000081.html' },
    { id: 43, title: '三郷市監査委員条例', category: '執行機関', keywords: ['監査', '監査委員', 'チェック機能'], summary: '監査委員に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000086.html' },
    { id: 44, title: '三郷市公平委員会設置条例', category: '執行機関', keywords: ['公平委員会', '職員', '救済'], summary: '公平委員会の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000090.html' },
    { id: 45, title: '三郷市人事行政の運営等の状況の公表に関する条例', category: '執行機関', keywords: ['人事行政', '公表', '透明性'], summary: '人事行政の状況公表に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000098.html' },
    { id: 46, title: '固定資産評価審査委員会条例', category: '執行機関', keywords: ['固定資産', '評価', '審査'], summary: '固定資産評価審査委員会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000101.html' },
    { id: 47, title: '三郷市附属機関に関する条例', category: '執行機関', keywords: ['附属機関', '審議会', '委員会'], summary: '市の附属機関に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000104.html' },

    // ===== 第4編 人事 =====
    { id: 48, title: '三郷市副市長の定数を定める条例', category: '人事', keywords: ['副市長', '定数', '特別職'], summary: '副市長の定数を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000106.html' },
    { id: 49, title: '三郷市職員定数条例', category: '人事', keywords: ['職員', '定数', '組織'], summary: '職員の定数を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000107.html' },
    { id: 50, title: '一般職の任期付職員の採用等に関する条例', category: '人事', keywords: ['任期付', '採用', '職員'], summary: '任期付職員の採用に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000110.html' },
    { id: 51, title: '職員の分限に関する手続及び効果に関する条例', category: '人事', keywords: ['分限', '処分', '職員'], summary: '職員の分限処分に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000113.html' },
    { id: 52, title: '三郷市職員の定年等に関する条例', category: '人事', keywords: ['定年', '退職', '職員'], summary: '職員の定年に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000115.html' },
    { id: 53, title: '公益的法人等への職員の派遣等に関する条例', category: '人事', keywords: ['派遣', '公益法人', '職員'], summary: '公益法人等への職員派遣に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000120.html' },
    { id: 54, title: '職員の懲戒の手続及び効果に関する条例', category: '人事', keywords: ['懲戒', '処分', '職員'], summary: '職員の懲戒処分に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000124.html' },
    { id: 55, title: '職員の服務の宣誓に関する条例', category: '人事', keywords: ['服務', '宣誓', '職員'], summary: '職員の服務宣誓に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000126.html' },
    { id: 56, title: '職務に専念する義務の特例に関する条例', category: '人事', keywords: ['職務専念義務', '特例', '職員'], summary: '職務専念義務の特例に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000127.html' },
    { id: 57, title: '職員の勤務時間、休日及び休暇に関する条例', category: '人事', keywords: ['勤務時間', '休日', '休暇', '働き方'], summary: '職員の勤務条件に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000130.html' },
    { id: 58, title: '職員の育児休業等に関する条例', category: '人事', keywords: ['育児休業', '育休', 'ワークライフバランス'], summary: '職員の育児休業に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000136.html' },
    { id: 59, title: '議会の議員その他非常勤の職員の公務災害補償等に関する条例', category: '人事', keywords: ['公務災害', '補償', '非常勤'], summary: '非常勤職員の公務災害補償に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000150.html' },
    { id: 60, title: '三郷市職員公務災害等見舞金支給条例', category: '人事', keywords: ['公務災害', '見舞金', '職員'], summary: '職員の公務災害見舞金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000156.html' },
    { id: 61, title: '職員団体の登録に関する条例', category: '人事', keywords: ['職員団体', '労働組合', '登録'], summary: '職員団体の登録に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000167.html' },

    // ===== 第5編 給与 =====
    { id: 62, title: '議会の議員の議員報酬及び費用弁償等に関する条例', category: '給与', keywords: ['議員報酬', '報酬', '議会'], summary: '議員の報酬に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000171.html' },
    { id: 63, title: '特別職の職員で非常勤のものの報酬及び費用弁償に関する条例', category: '給与', keywords: ['報酬', '非常勤', '特別職'], summary: '非常勤特別職の報酬に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000172.html' },
    { id: 64, title: '三郷市会計年度任用職員の報酬等に関する条例', category: '給与', keywords: ['会計年度任用職員', '報酬', '非正規'], summary: '会計年度任用職員の報酬に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000174.html' },
    { id: 65, title: '証人等の実費弁償に関する条例', category: '給与', keywords: ['証人', '実費弁償', '費用'], summary: '証人等の実費弁償に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000176.html' },
    { id: 66, title: '三郷市特別職報酬等審議会条例', category: '給与', keywords: ['特別職', '報酬', '審議会'], summary: '特別職報酬審議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000177.html' },
    { id: 67, title: '市長及び副市長の給与等に関する条例', category: '給与', keywords: ['市長', '副市長', '給与'], summary: '市長・副市長の給与に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000178.html' },
    { id: 68, title: '三郷市教育委員会教育長の給与等に関する条例', category: '給与', keywords: ['教育長', '給与', '教育委員会'], summary: '教育長の給与に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000181.html' },
    { id: 69, title: '職員の給与に関する条例', category: '給与', keywords: ['給与', '職員', '給料'], summary: '職員の給与に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000182.html' },
    { id: 70, title: '技能労務職員の給与の種類及び基準に関する条例', category: '給与', keywords: ['技能労務', '給与', '職員'], summary: '技能労務職員の給与に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000190.html' },
    { id: 71, title: '職員の特殊勤務手当に関する条例', category: '給与', keywords: ['特殊勤務', '手当', '職員'], summary: '特殊勤務手当に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000198.html' },
    { id: 72, title: '職員等の旅費に関する条例', category: '給与', keywords: ['旅費', '出張', '職員'], summary: '職員の旅費に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000206.html' },

    // ===== 第6編 財務 =====
    { id: 73, title: '議会の議決に付すべき契約及び財産の取得又は処分に関する条例', category: '財務', keywords: ['契約', '財産', '議会議決'], summary: '議会議決が必要な契約等に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000208.html' },
    { id: 74, title: '三郷市補助金等交付規則', category: '財務', keywords: ['補助金', '交付', '助成'], summary: '補助金の交付に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000210.html' },
    { id: 75, title: '財政事情の作成及び公表に関する条例', category: '財務', keywords: ['財政', '公表', '透明性'], summary: '財政状況の公表に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000211.html' },
    { id: 76, title: '三郷市税条例', category: '財務', keywords: ['市税', '住民税', '固定資産税', '税金'], summary: '市税に関する総合的な条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000214.html' },
    { id: 77, title: '三郷市都市計画税条例', category: '財務', keywords: ['都市計画税', '税金', '都市計画'], summary: '都市計画税に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000215.html' },
    { id: 78, title: '三郷市国民健康保険税条例', category: '財務', keywords: ['国保', '国民健康保険', '保険税'], summary: '国民健康保険税に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000216.html' },
    { id: 79, title: '三郷市財政調整基金条例', category: '財務', keywords: ['財政調整', '基金', '積立'], summary: '財政調整基金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000217.html' },
    { id: 80, title: '三郷市減債基金条例', category: '財務', keywords: ['減債', '基金', '借金返済'], summary: '減債基金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000218.html' },
    { id: 81, title: '三郷市公共施設整備基金条例', category: '財務', keywords: ['公共施設', '基金', '整備'], summary: '公共施設整備基金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000219.html' },
    { id: 82, title: '三郷市地域福祉基金条例', category: '財務', keywords: ['地域福祉', '基金', '福祉'], summary: '地域福祉基金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000220.html' },
    { id: 83, title: '三郷市国民健康保険財政調整基金条例', category: '財務', keywords: ['国保', '基金', '財政'], summary: '国民健康保険財政調整基金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000221.html' },
    { id: 84, title: '三郷市介護保険給付費支払基金条例', category: '財務', keywords: ['介護保険', '基金', '給付'], summary: '介護保険給付費支払基金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000224.html' },
    { id: 85, title: '三郷市みどりの基金条例', category: '財務', keywords: ['みどり', '基金', '緑化', '環境'], summary: 'みどりの基金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000228.html' },
    { id: 86, title: '財産の交換、譲与、無償貸付等に関する条例', category: '財務', keywords: ['財産', '交換', '貸付'], summary: '財産の交換等に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000229.html' },
    { id: 87, title: '三郷市長期継続契約を締結することができる契約を定める条例', category: '財務', keywords: ['長期継続契約', '契約', '調達'], summary: '長期継続契約に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000230.html' },

    // ===== 第7編 教育 =====
    { id: 88, title: '三郷市教育に関する事務の職務権限の特例に関する条例', category: '教育・文化', keywords: ['教育', '職務権限', '特例'], summary: '教育事務の職務権限の特例に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000236.html' },
    { id: 89, title: '三郷市就学支援委員会規則', category: '教育・文化', keywords: ['就学', '支援', '教育'], summary: '就学支援委員会に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000245.html' },
    { id: 90, title: '三郷市人権教育推進協議会条例', category: '教育・文化', keywords: ['人権', '教育', '推進'], summary: '人権教育推進協議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000246.html' },
    { id: 91, title: '三郷市立学校設置及び管理に関する条例', category: '教育・文化', keywords: ['学校', '設置', '小中学校'], summary: '市立学校の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000248.html' },
    { id: 92, title: '三郷市学校運営協議会規則', category: '教育・文化', keywords: ['学校運営', 'コミュニティスクール', '協議会'], summary: '学校運営協議会（コミュニティスクール）に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000254.html' },
    { id: 93, title: '三郷市いじめ問題対策連絡協議会条例', category: '教育・文化', keywords: ['いじめ', '対策', '連絡協議会'], summary: 'いじめ問題対策連絡協議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000255.html' },
    { id: 94, title: '三郷市いじめ問題調査委員会条例', category: '教育・文化', keywords: ['いじめ', '調査', '委員会'], summary: 'いじめ問題調査委員会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000257.html' },
    { id: 95, title: '三郷市いじめ問題再調査委員会条例', category: '教育・文化', keywords: ['いじめ', '再調査', '委員会'], summary: 'いじめ問題再調査委員会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000259.html' },
    { id: 96, title: '三郷市入学準備金貸付条例', category: '教育・文化', keywords: ['入学', '準備金', '貸付', '奨学金'], summary: '入学準備金の貸付に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000268.html' },
    { id: 97, title: '三郷市立学校給食センター設置及び管理条例', category: '教育・文化', keywords: ['給食', 'センター', '学校給食'], summary: '学校給食センターの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000275.html' },
    { id: 98, title: '三郷市社会教育委員設置条例', category: '教育・文化', keywords: ['社会教育', '委員', '生涯学習'], summary: '社会教育委員の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000280.html' },
    { id: 99, title: '三郷市立公民館設置及び管理条例', category: '教育・文化', keywords: ['公民館', '設置', '生涯学習'], summary: '公民館の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000282.html' },
    { id: 100, title: '三郷市図書館設置及び管理条例', category: '教育・文化', keywords: ['図書館', '読書', '設置', '文化'], summary: '図書館の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000284.html' },
    { id: 101, title: '三郷市郷土資料館設置及び管理条例', category: '教育・文化', keywords: ['郷土資料館', '歴史', '文化財'], summary: '郷土資料館の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000287.html' },
    { id: 102, title: '三郷市青少年ホーム設置及び管理条例', category: '教育・文化', keywords: ['青少年', 'ホーム', '若者支援'], summary: '青少年ホームの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000291.html' },
    { id: 103, title: '三郷市青少年問題協議会条例', category: '教育・文化', keywords: ['青少年', '問題', '協議会'], summary: '青少年問題協議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000293.html' },
    { id: 104, title: '三郷市スポーツ推進審議会条例', category: '教育・文化', keywords: ['スポーツ', '推進', '審議会'], summary: 'スポーツ推進審議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000297.html' },
    { id: 105, title: '三郷市スポーツ推進委員設置条例', category: '教育・文化', keywords: ['スポーツ', '推進委員', '地域'], summary: 'スポーツ推進委員の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000298.html' },
    { id: 106, title: '三郷市体育館設置及び管理条例', category: '教育・文化', keywords: ['体育館', 'スポーツ施設', '設置'], summary: '体育館の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000300.html' },
    { id: 107, title: '三郷市立小・中学校体育施設の開放に関する規則', category: '教育・文化', keywords: ['学校開放', '体育施設', 'スポーツ'], summary: '学校体育施設の開放に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000303.html' },
    { id: 108, title: '三郷市文化財保護条例', category: '教育・文化', keywords: ['文化財', '保護', '歴史', '伝統'], summary: '文化財の保護に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000308.html' },

    // ===== 第8編 民生 =====
    { id: 109, title: '三郷市福祉事務所設置条例', category: '民生・福祉', keywords: ['福祉事務所', '社会福祉', '生活保護'], summary: '福祉事務所の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000312.html' },
    { id: 110, title: '三郷市社会福祉法人の助成に関する条例', category: '民生・福祉', keywords: ['社会福祉法人', '助成', '福祉'], summary: '社会福祉法人への助成に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000318.html' },
    { id: 111, title: '三郷市児童発達支援センター設置及び管理条例', category: '民生・福祉', keywords: ['児童発達支援', '障害児', '療育'], summary: '児童発達支援センターの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000335.html' },
    { id: 112, title: '三郷市保育所設置及び管理条例', category: '民生・福祉', keywords: ['保育所', '保育', '子育て'], summary: '保育所の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000340.html' },
    { id: 113, title: '三郷市地域型保育事業の設備及び運営の基準に関する条例', category: '民生・福祉', keywords: ['地域型保育', '小規模保育', '子育て'], summary: '地域型保育事業の基準に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000354.html' },
    { id: 114, title: '三郷市放課後児童健全育成事業の設備及び運営の基準に関する条例', category: '民生・福祉', keywords: ['放課後', '児童クラブ', '学童'], summary: '放課後児童クラブの基準に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000356.html' },
    { id: 115, title: '三郷市子ども・子育て会議条例', category: '民生・福祉', keywords: ['子ども', '子育て', '会議'], summary: '子ども・子育て会議に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000360.html' },
    { id: 116, title: '三郷市立児童館設置及び管理条例', category: '民生・福祉', keywords: ['児童館', '子ども', '居場所'], summary: '児童館の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000361.html' },
    { id: 117, title: '三郷市児童遊園設置条例', category: '民生・福祉', keywords: ['児童遊園', '公園', '子ども'], summary: '児童遊園の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000365.html' },
    { id: 118, title: '三郷市児童クラブ設置及び管理条例', category: '民生・福祉', keywords: ['児童クラブ', '学童', '放課後'], summary: '児童クラブの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000369.html' },
    { id: 119, title: '三郷市こども医療費支給に関する条例', category: '民生・福祉', keywords: ['子ども', '医療費', '助成', '子育て支援'], summary: '子どもの医療費助成に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000381.html' },
    { id: 120, title: '三郷市ひとり親家庭等の医療費の支給に関する条例', category: '民生・福祉', keywords: ['ひとり親', '医療費', '助成', '母子家庭'], summary: 'ひとり親家庭の医療費助成に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000383.html' },
    { id: 121, title: '三郷市老人デイサービスセンター設置及び管理条例', category: '民生・福祉', keywords: ['高齢者', 'デイサービス', '介護'], summary: '老人デイサービスセンターの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000390.html' },
    { id: 122, title: '三郷市老人福祉センター設置及び管理条例', category: '民生・福祉', keywords: ['高齢者', '福祉センター', '交流'], summary: '老人福祉センターの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000392.html' },
    { id: 123, title: '三郷市後期高齢者医療に関する条例', category: '民生・福祉', keywords: ['後期高齢者', '医療', '保険'], summary: '後期高齢者医療に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000400.html' },
    { id: 124, title: '三郷市障害支援区分審査会の委員の定数等を定める条例', category: '民生・福祉', keywords: ['障害', '支援区分', '審査会'], summary: '障害支援区分審査会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000415.html' },
    { id: 125, title: '三郷市障がい者福祉施設みさと設置及び管理条例', category: '民生・福祉', keywords: ['障害者', '福祉施設', '支援'], summary: '障がい者福祉施設みさとの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000419.html' },
    { id: 126, title: '三郷市障がい者等の利用に係る公の施設使用料減免条例', category: '民生・福祉', keywords: ['障害者', '減免', '公共施設'], summary: '障がい者等の施設使用料減免に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000429.html' },
    { id: 127, title: '三郷市こころつながる手話言語条例', category: '民生・福祉', keywords: ['手話', '言語', '障害者', 'コミュニケーション'], summary: '手話言語に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000437.html' },
    { id: 128, title: '三郷市重度心身障害者医療費支給に関する条例', category: '民生・福祉', keywords: ['重度障害', '医療費', '助成'], summary: '重度心身障害者の医療費助成に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000439.html' },
    { id: 129, title: '三郷市在宅重度心身障害者手当支給条例', category: '民生・福祉', keywords: ['在宅', '重度障害', '手当'], summary: '在宅重度心身障害者手当に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000441.html' },
    { id: 130, title: '三郷市国民健康保険条例', category: '民生・福祉', keywords: ['国民健康保険', '国保', '医療保険'], summary: '国民健康保険に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000450.html' },
    { id: 131, title: '三郷市介護保険条例', category: '民生・福祉', keywords: ['介護保険', '介護', '高齢者'], summary: '介護保険に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000456.html' },
    { id: 132, title: '三郷市介護認定審査会規則', category: '民生・福祉', keywords: ['介護認定', '審査会', '要介護'], summary: '介護認定審査会に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000464.html' },
    { id: 133, title: '三郷市指定居宅介護支援等の事業の人員及び運営等に関する基準を定める条例', category: '民生・福祉', keywords: ['居宅介護', 'ケアマネジャー', '介護支援'], summary: '居宅介護支援事業の基準に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000467.html' },
    { id: 134, title: '三郷市指定地域密着型サービスの事業の人員、設備及び運営等に関する基準を定める条例', category: '民生・福祉', keywords: ['地域密着型', '介護サービス', '基準'], summary: '地域密着型サービスの基準に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000471.html' },
    { id: 135, title: '三郷市地域包括支援センターの包括的支援事業の実施に関する基準を定める条例', category: '民生・福祉', keywords: ['地域包括', '支援センター', '高齢者'], summary: '地域包括支援センターの基準に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000473.html' },
    { id: 136, title: '三郷市健康推進協議会条例', category: '民生・福祉', keywords: ['健康', '推進', '協議会'], summary: '健康推進協議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000480.html' },
    { id: 137, title: '三郷市健康福祉会館設置及び管理条例', category: '民生・福祉', keywords: ['健康', '福祉会館', '施設'], summary: '健康福祉会館の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000483.html' },
    { id: 138, title: '三郷市動物の愛護及び管理に関する条例', category: '民生・福祉', keywords: ['動物', '愛護', 'ペット'], summary: '動物の愛護・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000497.html' },
    { id: 139, title: '三郷市廃棄物の処理及び再利用並びに資源物の持ち去り防止に関する条例', category: '民生・福祉', keywords: ['廃棄物', 'ごみ', 'リサイクル', '再利用'], summary: '廃棄物処理・再利用に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000501.html' },
    { id: 140, title: '三郷市墓地等の経営の許可等に関する条例', category: '民生・福祉', keywords: ['墓地', '霊園', '経営許可'], summary: '墓地の経営許可に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000513.html' },
    { id: 141, title: '三郷市ペット霊園の設置の許可等に関する条例', category: '民生・福祉', keywords: ['ペット', '霊園', '許可'], summary: 'ペット霊園の設置許可に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000515.html' },
    { id: 142, title: '三郷市公害防止条例', category: '民生・福祉', keywords: ['公害', '環境', '防止'], summary: '公害防止に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000517.html' },
    { id: 143, title: '三郷市環境基本条例', category: '民生・福祉', keywords: ['環境', '基本条例', '持続可能'], summary: '環境保全の基本理念を定める条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000519.html' },
    { id: 144, title: '三郷市あき地の雑草等の除去に関する条例', category: '民生・福祉', keywords: ['空き地', '雑草', '環境美化'], summary: '空き地の雑草除去に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000523.html' },
    { id: 145, title: '三郷市空き缶等の散乱防止に関する条例', category: '民生・福祉', keywords: ['空き缶', '散乱防止', '美化'], summary: '空き缶等の散乱防止に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000525.html' },
    { id: 146, title: '三郷市ラブホテルの建築規制に関する条例', category: '民生・福祉', keywords: ['ラブホテル', '建築規制', '風営'], summary: 'ラブホテルの建築規制に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000527.html' },
    { id: 147, title: '三郷市市民パブリック・コメント手続条例', category: '民生・福祉', keywords: ['パブリックコメント', '市民参加', '意見募集'], summary: 'パブリックコメント手続に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000531.html' },
    { id: 148, title: '三郷市男女共同参画社会づくり条例', category: '民生・福祉', keywords: ['男女共同参画', 'ジェンダー', '平等'], summary: '男女共同参画社会づくりに関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000534.html' },
    { id: 149, title: '三郷市印鑑条例', category: '民生・福祉', keywords: ['印鑑', '登録', '証明'], summary: '印鑑登録に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000540.html' },
    { id: 150, title: '三郷市防災会議条例', category: '民生・福祉', keywords: ['防災', '会議', '災害対策'], summary: '防災会議に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000544.html' },
    { id: 151, title: '三郷市災害対策本部条例', category: '民生・福祉', keywords: ['災害', '対策本部', '緊急'], summary: '災害対策本部に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000546.html' },
    { id: 152, title: '三郷市防災センター設置及び管理条例', category: '民生・福祉', keywords: ['防災', 'センター', '施設'], summary: '防災センターの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000552.html' },
    { id: 153, title: '三郷市国民保護対策本部及び三郷市緊急対処事態対策本部に関する条例', category: '民生・福祉', keywords: ['国民保護', '緊急事態', '対策本部'], summary: '国民保護対策本部に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000554.html' },
    { id: 154, title: '三郷市国民保護協議会条例', category: '民生・福祉', keywords: ['国民保護', '協議会', '安全'], summary: '国民保護協議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000555.html' },
    { id: 155, title: '三郷市新型インフルエンザ等対策本部条例', category: '民生・福祉', keywords: ['新型インフルエンザ', '対策', '感染症'], summary: '新型インフルエンザ等対策本部に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000557.html' },
    { id: 156, title: '三郷市災害派遣手当等の支給に関する条例', category: '民生・福祉', keywords: ['災害派遣', '手当', '支援'], summary: '災害派遣手当の支給に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000559.html' },
    { id: 157, title: '三郷市自転車等の放置の防止に関する条例', category: '民生・福祉', keywords: ['自転車', '放置', '駐輪'], summary: '自転車等の放置防止に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000561.html' },
    { id: 158, title: '三郷市防犯のまちづくり推進条例', category: '民生・福祉', keywords: ['防犯', 'まちづくり', '安全'], summary: '防犯のまちづくり推進に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000571.html' },
    { id: 159, title: '三郷市犯罪被害者等支援条例', category: '民生・福祉', keywords: ['犯罪被害者', '支援', '救済'], summary: '犯罪被害者支援に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000572.html' },
    { id: 160, title: '三郷市振り込め詐欺等の被害防止に関する条例', category: '民生・福祉', keywords: ['振り込め詐欺', '詐欺', '被害防止'], summary: '振り込め詐欺被害防止に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000577.html' },
    { id: 161, title: '三郷市空家等の適切な管理に関する条例', category: '民生・福祉', keywords: ['空き家', '管理', '防犯'], summary: '空き家の適切な管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000578.html' },
    { id: 162, title: '三郷市暴力団排除条例', category: '民生・福祉', keywords: ['暴力団', '排除', '安全'], summary: '暴力団排除に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000580.html' },
    { id: 163, title: '三郷市住居表示に関する条例', category: '民生・福祉', keywords: ['住居表示', '住所', '地番'], summary: '住居表示に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000581.html' },
    { id: 164, title: '三郷市文化会館設置及び管理条例', category: '民生・福祉', keywords: ['文化会館', '施設', '文化活動'], summary: '文化会館の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000583.html' },
    { id: 165, title: '三郷市立コミュニティセンター設置及び管理条例', category: '民生・福祉', keywords: ['コミュニティセンター', '地域活動', '施設'], summary: 'コミュニティセンターの設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000585.html' },
    { id: 166, title: '三郷市斎場条例', category: '民生・福祉', keywords: ['斎場', '火葬場', '葬祭'], summary: '斎場に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000599.html' },
    { id: 167, title: '災害弔慰金の支給等に関する条例', category: '民生・福祉', keywords: ['災害', '弔慰金', '支援'], summary: '災害弔慰金の支給に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000601.html' },
    { id: 168, title: '三郷市災害見舞金支給条例', category: '民生・福祉', keywords: ['災害', '見舞金', '支援'], summary: '災害見舞金の支給に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000603.html' },

    // ===== 第9編 産業経済 =====
    { id: 169, title: '三郷市農業委員会の委員及び農地利用最適化推進委員の定数に関する条例', category: '産業経済', keywords: ['農業委員会', '農地', '委員'], summary: '農業委員会の委員定数に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000605.html' },
    { id: 170, title: '三郷市農政審議会条例', category: '産業経済', keywords: ['農政', '審議会', '農業'], summary: '農政審議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000610.html' },
    { id: 171, title: '三郷市営土地改良事業受益者負担金徴収条例', category: '産業経済', keywords: ['土地改良', '受益者負担', '農業基盤'], summary: '土地改良事業の受益者負担金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000612.html' },
    { id: 172, title: '農業近代化資金利子補給条例', category: '産業経済', keywords: ['農業', '近代化', '融資', '利子補給'], summary: '農業近代化資金の利子補給に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000614.html' },
    { id: 173, title: '三郷市商工審議会条例', category: '産業経済', keywords: ['商工', '審議会', '産業振興'], summary: '商工審議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000622.html' },
    { id: 174, title: '三郷市中小企業融資条例', category: '産業経済', keywords: ['中小企業', '融資', '経営支援'], summary: '中小企業融資に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000624.html' },
    { id: 175, title: '三郷市家内労働者生業資金貸付条例', category: '産業経済', keywords: ['家内労働', '貸付', '資金'], summary: '家内労働者への生業資金貸付に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000637.html' },
    { id: 176, title: '三郷市消費生活センターの組織及び運営等に関する条例', category: '産業経済', keywords: ['消費生活', 'センター', '相談'], summary: '消費生活センターに関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000641.html' },

    // ===== 第10編 建設 =====
    { id: 177, title: '三郷市道路の構造、管理及び占用に関する条例', category: '建設', keywords: ['道路', '管理', '占用'], summary: '道路の構造・管理・占用に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000652.html' },
    { id: 178, title: '三郷市道路占用料条例', category: '建設', keywords: ['道路', '占用料', '使用料'], summary: '道路占用料に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000657.html' },
    { id: 179, title: '三郷市市道に設置する道路標識の寸法に関する条例', category: '建設', keywords: ['道路標識', '寸法', '基準'], summary: '道路標識の寸法に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000658.html' },
    { id: 180, title: '三郷市準用河川条例', category: '建設', keywords: ['準用河川', '河川', '管理'], summary: '準用河川に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000660.html' },
    { id: 181, title: '三郷市都市計画審議会条例', category: '建設', keywords: ['都市計画', '審議会', 'まちづくり'], summary: '都市計画審議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000669.html' },
    { id: 182, title: '三郷市開発事業等の手続等に関する条例', category: '建設', keywords: ['開発', '手続', '宅地造成'], summary: '開発事業の手続に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000672.html' },
    { id: 183, title: '三郷市地区計画等の案の作成手続に関する条例', category: '建設', keywords: ['地区計画', 'まちづくり', '都市計画'], summary: '地区計画の作成手続に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000676.html' },
    { id: 184, title: '三郷市都市計画法に基づく開発許可等の基準に関する条例', category: '建設', keywords: ['開発許可', '都市計画', '基準'], summary: '開発許可の基準に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000677.html' },
    { id: 185, title: '三郷市景観条例', category: '建設', keywords: ['景観', 'まちなみ', '美しいまち'], summary: '景観保全に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000679.html' },
    { id: 186, title: '三郷市生産緑地地区の区域の規模に関する条件を定める条例', category: '建設', keywords: ['生産緑地', '農地', '都市農業'], summary: '生産緑地の規模条件に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000685.html' },
    { id: 187, title: '三郷市みどりの条例', category: '建設', keywords: ['みどり', '緑化', '環境'], summary: 'みどりの保全・創出に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000686.html' },
    { id: 188, title: '三郷市屋外広告物条例', category: '建設', keywords: ['屋外広告', '看板', '景観'], summary: '屋外広告物に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000692.html' },
    { id: 189, title: '三郷市都市公園条例', category: '建設', keywords: ['公園', '都市公園', 'みどり'], summary: '都市公園に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000694.html' },
    { id: 190, title: '三郷市公園運営委員会条例', category: '建設', keywords: ['公園', '運営', '委員会'], summary: '公園運営委員会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000696.html' },
    { id: 191, title: '三郷市運動公園の設置及び管理に関する条例', category: '建設', keywords: ['運動公園', 'スポーツ', '施設'], summary: '運動公園の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000698.html' },
    { id: 192, title: '三郷市公共下水道事業の設置等に関する条例', category: '建設', keywords: ['下水道', '公共下水道', 'インフラ'], summary: '公共下水道事業に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000703.html' },
    { id: 193, title: '三郷市下水道事業審議会条例', category: '建設', keywords: ['下水道', '審議会', 'インフラ'], summary: '下水道事業審議会に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000704.html' },
    { id: 194, title: '三郷市公共下水道の構造等の技術上の基準に関する条例', category: '建設', keywords: ['下水道', '基準', '技術'], summary: '公共下水道の技術基準に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000706.html' },
    { id: 195, title: '三郷市下水道条例', category: '建設', keywords: ['下水道', '使用', '排水'], summary: '下水道の使用等に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000708.html' },
    { id: 196, title: '三郷都市計画下水道事業受益者負担に関する条例', category: '建設', keywords: ['下水道', '受益者負担', '負担金'], summary: '下水道事業受益者負担に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000710.html' },
    { id: 197, title: '三郷市公共下水道使用料条例', category: '建設', keywords: ['下水道', '使用料', '料金'], summary: '公共下水道使用料に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000712.html' },
    { id: 198, title: '三郷市地区計画区域内における建築物等の制限に関する条例', category: '建設', keywords: ['地区計画', '建築制限', 'まちづくり'], summary: '地区計画区域内の建築制限に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000722.html' },
    { id: 199, title: '三郷市建築協定条例', category: '建設', keywords: ['建築協定', 'まちなみ', '住環境'], summary: '建築協定に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000724.html' },
    { id: 200, title: '三郷市特別工業地区条例', category: '建設', keywords: ['工業地区', '用途地域', '建築'], summary: '特別工業地区に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000727.html' },
    { id: 201, title: '三郷市建築基準法の規定に基づく建築物の建築等に係る確認申請手数料等の徴収に関する条例', category: '建設', keywords: ['建築確認', '手数料', '建築基準法'], summary: '建築確認申請手数料に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000731.html' },
    { id: 202, title: '三郷市市営住宅設置及び管理条例', category: '建設', keywords: ['市営住宅', '公営住宅', '住宅'], summary: '市営住宅の設置・管理に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000737.html' },

    // ===== 第11編 水道 =====
    { id: 203, title: '三郷市水道事業の設置等に関する条例', category: '水道', keywords: ['水道', '事業', '設置'], summary: '水道事業の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000740.html' },
    { id: 204, title: '三郷市企業職員の給与の種類及び基準に関する条例', category: '水道', keywords: ['企業職員', '給与', '水道'], summary: '企業職員の給与に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000749.html' },
    { id: 205, title: '三郷市水道事業給水条例', category: '水道', keywords: ['給水', '水道', '使用'], summary: '水道の給水に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000762.html' },
    { id: 206, title: '三郷市水道事業の布設工事監督者及び水道技術管理者に関する条例', category: '水道', keywords: ['水道', '監督者', '技術管理'], summary: '水道の布設工事監督者等に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000767.html' },

    // ===== 第12編 消防 =====
    { id: 207, title: '三郷市消防本部及び消防署の設置に関する条例', category: '消防', keywords: ['消防', '消防署', '設置'], summary: '消防本部・消防署の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000769.html' },
    { id: 208, title: '三郷市消防長に対する事務委任に関する規則', category: '消防', keywords: ['消防長', '事務委任', '消防'], summary: '消防長への事務委任に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000775.html' },
    { id: 209, title: '三郷市消防長及び消防署長の資格を定める条例', category: '消防', keywords: ['消防長', '消防署長', '資格'], summary: '消防長等の資格に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000776.html' },
    { id: 210, title: '三郷市消防職員の特殊勤務手当に関する条例', category: '消防', keywords: ['消防職員', '特殊勤務', '手当'], summary: '消防職員の特殊勤務手当に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000790.html' },
    { id: 211, title: '三郷市消防賞じゅつ金及び殉職者特別賞じゅつ金条例', category: '消防', keywords: ['消防', '賞じゅつ金', '殉職'], summary: '消防賞じゅつ金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000791.html' },
    { id: 212, title: '三郷市消防事務に係る手数料徴収条例', category: '消防', keywords: ['消防', '手数料', '許可'], summary: '消防事務の手数料に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000801.html' },
    { id: 213, title: '三郷市火災予防条例', category: '消防', keywords: ['火災', '予防', '防火'], summary: '火災予防に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000803.html' },
    { id: 214, title: '三郷市消防団の設置等に関する条例', category: '消防', keywords: ['消防団', '設置', '消防'], summary: '消防団の設置に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000817.html' },
    { id: 215, title: '三郷市消防団員の定員、任免、給与、服務等に関する条例', category: '消防', keywords: ['消防団員', '定員', '給与'], summary: '消防団員の身分等に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000820.html' },
    { id: 216, title: '三郷市非常勤消防団員に係る退職報償金の支給に関する条例', category: '消防', keywords: ['消防団員', '退職報償金', '非常勤'], summary: '消防団員の退職報償金に関する条例。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000827.html' },
    { id: 217, title: '三郷市消防委員会規則', category: '消防', keywords: ['消防', '委員会', '審議'], summary: '消防委員会に関する規則。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000829.html' },

    // ===== 第13編 その他 =====
    { id: 218, title: '埼玉県市町村総合事務組合規約', category: 'その他', keywords: ['事務組合', '広域', '連携'], summary: '埼玉県市町村総合事務組合の規約。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000831.html' },
    { id: 219, title: '江戸川水防事務組合規約', category: 'その他', keywords: ['水防', '事務組合', '江戸川'], summary: '江戸川水防事務組合の規約。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000832.html' },
    { id: 220, title: '東埼玉資源環境組合規約', category: 'その他', keywords: ['資源環境', '事務組合', 'ごみ処理'], summary: '東埼玉資源環境組合の規約。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000833.html' },
    { id: 221, title: '彩の国さいたま人づくり広域連合規約', category: 'その他', keywords: ['広域連合', '人材育成', '研修'], summary: '彩の国さいたま人づくり広域連合の規約。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000834.html' },
    { id: 222, title: '埼玉県後期高齢者医療広域連合規約', category: 'その他', keywords: ['後期高齢者', '広域連合', '医療'], summary: '埼玉県後期高齢者医療広域連合の規約。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000835.html' },
    { id: 223, title: '三郷市土地開発公社定款', category: 'その他', keywords: ['土地開発公社', '公社', '土地'], summary: '三郷市土地開発公社の定款。', url: 'https://www1.g-reiki.net/misato/reiki_honbun/z600RG00000836.html' }
];

// カテゴリリスト
const ordinanceCategories = [
    'all',
    '総規・基本',
    '議会',
    '執行機関',
    '人事',
    '給与',
    '財務',
    '教育・文化',
    '民生・福祉',
    '産業経済',
    '建設',
    '水道',
    '消防',
    'その他'
];
